[workspace]

members = [
	"common",
	"day1",
	"day1_2",
	"day2",
	"day2_2",
	"day3",
	"day3_2",
	"day4",
	"day5",
	"day5_2",
	"day6",
	"day6_2",
	"day7",
	"day8",
	"day9",
	"day10",
	"day11",
	"day12",
	"day13",
	"day14",
	"day15",
	"day16"
]
